export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// RESTAURANTS
export const RESTAURANT_SAVED = "RESTAURANT_SAVED";
export const RESTAURANT_QUERIED = "RESTAURANT_QUERIED";

// BOOKING
export const SWITCH_MODE = "SWITCH_MODE";
export const SELECT_SERVICE_PROVIDER = "SELECT_SERVICE_PROVIDER";
export const SELECT_SERVICE = "SELECT_SERVICE";
export const SERVICES_FILTERED = "SERVICES_FILTERED";
export const NEW_PRICE_LIST_ITEM = "NEW_PRICE_LIST_ITEM";
export const PRICE_LIST_QUERIED = "PRICE_LIST_QUERIED";
export const PRICE_LIST_ITEM_DELETED = "PRICE_LIST_ITEM_DELETED";
export const UPDATE_PRICE_LIST_ITEM = "UPDATE_PRICE_LIST_ITEM";
export const BOOKING_SAVED = "BOOKING_SAVED";
export const BOOKINGS_QUERIED = "BOOKINGS_QUERIED";
export const BOOKING_DELETED = "BOOKING_DELETED";

export const SELECT_FUNCTIONALITY = "SELECT_FUNCTIONALITY";