apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-ui-prefixed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: security-ui-service
              servicePort: 8200
          - path: /oauth2
            pathType: ImplementationSpecific
            backend:
              serviceName: security-ui-service
              servicePort: 8200