apiVersion: v1
name: jenkins
home: https://jenkins.io/
version: 2.15.0
appVersion: lts
description: Open source continuous integration server. It supports multiple SCM tools
  including CVS, Subversion and Git. It can execute Apache Ant and Apache Maven-based
  projects as well as arbitrary scripts.
sources:
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker-jnlp-slave
- https://github.com/maorfr/kube-tasks
- https://github.com/jenkinsci/configuration-as-code-plugin
maintainers:
- name: maorfr
  email: maor.friedman@redhat.com
- name: torstenwalter
  email: mail@torstenwalter.de
- name: mogaal
  email: garridomota@gmail.com
- name: wmcdona89
  email: wmcdona89@gmail.com
- name: timja
  email: timjacomb1@gmail.com
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
    - name: Jenkins
      url: https://www.jenkins.io/
