spring:
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:30001/postgres?currentSchema=booking}
        username: postgres
        password: postgres

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                ddl-auto: update
                jdbc:
                  lob:
                    non_contextual_creation: true
app:
    authorizationEndpoint: ${AUTHORIZATION_ENDPOINT:http://localhost:8102}
    auth:
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
        tokenExpirationMsec: 864000000